# Generated by Django 5.0.8 on 2024-08-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.DeleteModel(
            name='Referencias',
        ),
    ]
